//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.11.12 at 03:57:02 PM UTC 
//


package candy;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for candy complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="candy">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="energy" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="type">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Caramel"/>
 *               &lt;enumeration value="Iris"/>
 *               &lt;enumeration value="Chocolate"/>
 *               &lt;enumeration value="ChocolateWithFilling"/>
 *               &lt;enumeration value="ChocolateWithoutFilling"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ingredients">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="water" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *                   &lt;element name="sugar" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *                   &lt;element name="fructose" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *                   &lt;element name="chocolateType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="vanillin" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="value">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="proteins" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="fats" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="carbohydrates" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="production" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "candy", propOrder = {
    "name",
    "energy",
    "type",
    "ingredients",
    "value",
    "production"
})
public class Candy {

    @XmlElement(required = true)
    protected String name;
    protected int energy;
    @XmlElement(required = true)
    protected String type;
    @XmlElement(required = true)
    protected Candy.Ingredients ingredients;
    @XmlElement(required = true)
    protected Candy.Value value;
    @XmlElement(required = true)
    protected String production;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    public Candy(){
        this.ingredients = new Candy.Ingredients();
        this.value = new Candy.Value();
    }

    public Candy(String id, String name, int energy, String type, String production,
                 float water, float sugar, float fructose, String chocolateType,
                 float vanillin, float proteins, float fats, float carbohydrates) {
        this.id = id;
        this.name = name;
        this.energy = energy;
        this.type = type;
        this.production = production;
        this.ingredients = new Ingredients(water, sugar, fructose, chocolateType,vanillin); // Инициализация ingredients с параметрами
        this.value = new Candy.Value(proteins, fats, carbohydrates);
    }
    @Override
    public String toString() {
        return "Candy{" +
                "id='" + id + '\'' +
                ", name='" + name + '\'' +
                ", energy=" + energy +
                ", type='" + type + '\'' +
                ", production='" + production + '\'' +
                ", proteins=" + this.value.proteins +
                ", fats=" + this.value.fats +
                ", carbohydrates=" + this.value.carbohydrates +
                ", ingredients=" + ingredients.toString() +
                '}';
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the energy property.
     * 
     */
    public int getEnergy() {
        return energy;
    }

    /**
     * Sets the value of the energy property.
     * 
     */
    public void setEnergy(int value) {
        this.energy = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the ingredients property.
     * 
     * @return
     *     possible object is
     *     {@link Candy.Ingredients }
     *     
     */
    public Candy.Ingredients getIngredients() {
        return ingredients;
    }

    /**
     * Sets the value of the ingredients property.
     * 
     * @param value
     *     allowed object is
     *     {@link Candy.Ingredients }
     *     
     */
    public void setIngredients(Candy.Ingredients value) {
        this.ingredients = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link Candy.Value }
     *     
     */
    public Candy.Value getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link Candy.Value }
     *     
     */
    public void setValue(Candy.Value value) {
        this.value = value;
    }

    public void setProteins(float proteins) {
        this.value.setProteins(proteins);
    };
    public void setFats(float fats) {
        this.value.setFats(fats);
    };
    public void setCarbohydrates(float carbohydrates) {
        this.value.setCarbohydrates(carbohydrates);
    };
    /**
     * Gets the value of the production property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProduction() {
        return production;
    }

    /**
     * Sets the value of the production property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProduction(String value) {
        this.production = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="water" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
     *         &lt;element name="sugar" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
     *         &lt;element name="fructose" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
     *         &lt;element name="chocolateType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="vanillin" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "water",
        "sugar",
        "fructose",
        "chocolateType",
        "vanillin"
    })
    public static class Ingredients {

        protected Float water;
        protected Float sugar;
        protected Float fructose;
        protected String chocolateType;
        protected Float vanillin;


        public Ingredients(float water, float sugar, float fructose, String chocolateType,float vanillin) {
            this.water = water;
            this.sugar = sugar;
            this.fructose = fructose;
            this.chocolateType = chocolateType;
            this.vanillin = vanillin;
        }
        public Ingredients() {}

        @Override
        public String toString() {
            return "Ingredients{" +
                    "water=" + water +
                    ", sugar=" + sugar +
                    ", fructose=" + fructose +
                    ", chocolateType='" + chocolateType + '\'' +
                    ", vanillin=" + vanillin +
                    '}';
        }

        /**
         * Gets the value of the water property.
         * 
         * @return
         *     possible object is
         *     {@link Float }
         *     
         */
        public Float getWater() {
            return water;
        }

        /**
         * Sets the value of the water property.
         * 
         * @param value
         *     allowed object is
         *     {@link Float }
         *     
         */
        public void setWater(Float value) {
            this.water = value;
        }

        /**
         * Gets the value of the sugar property.
         * 
         * @return
         *     possible object is
         *     {@link Float }
         *     
         */
        public Float getSugar() {
            return sugar;
        }

        /**
         * Sets the value of the sugar property.
         * 
         * @param value
         *     allowed object is
         *     {@link Float }
         *     
         */
        public void setSugar(Float value) {
            this.sugar = value;
        }

        /**
         * Gets the value of the fructose property.
         * 
         * @return
         *     possible object is
         *     {@link Float }
         *     
         */
        public Float getFructose() {
            return fructose;
        }

        /**
         * Sets the value of the fructose property.
         * 
         * @param value
         *     allowed object is
         *     {@link Float }
         *     
         */
        public void setFructose(Float value) {
            this.fructose = value;
        }

        /**
         * Gets the value of the chocolateType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getChocolateType() {
            return chocolateType;
        }

        /**
         * Sets the value of the chocolateType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setChocolateType(String value) {
            this.chocolateType = value;
        }

        /**
         * Gets the value of the vanillin property.
         * 
         * @return
         *     possible object is
         *     {@link Float }
         *     
         */
        public Float getVanillin() {
            return vanillin;
        }

        /**
         * Sets the value of the vanillin property.
         * 
         * @param value
         *     allowed object is
         *     {@link Float }
         *     
         */
        public void setVanillin(Float value) {
            this.vanillin = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="proteins" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *         &lt;element name="fats" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *         &lt;element name="carbohydrates" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "proteins",
        "fats",
        "carbohydrates"
    })
    public static class Value {

        protected float proteins;
        protected float fats;
        protected float carbohydrates;

        public Value(float proteins, float fats, float carbohydrates) {
            this.proteins = proteins;
            this.fats = fats;
            this.carbohydrates = carbohydrates;
        }
        public Value(){}

        /**
         * Gets the value of the proteins property.
         * 
         */
        public float getProteins() {
            return proteins;
        }

        /**
         * Sets the value of the proteins property.
         * 
         */
        public void setProteins(float value) {
            this.proteins = value;
        }

        /**
         * Gets the value of the fats property.
         * 
         */
        public float getFats() {
            return fats;
        }

        /**
         * Sets the value of the fats property.
         * 
         */
        public void setFats(float value) {
            this.fats = value;
        }

        /**
         * Gets the value of the carbohydrates property.
         * 
         */
        public float getCarbohydrates() {
            return carbohydrates;
        }

        /**
         * Sets the value of the carbohydrates property.
         * 
         */
        public void setCarbohydrates(float value) {
            this.carbohydrates = value;
        }

    }

}
