//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.11.04 at 03:27:22 PM UTC 
//


package candy;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="candy" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="energy" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="type">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="Caramel"/>
 *                         &lt;enumeration value="Iris"/>
 *                         &lt;enumeration value="Chocolate"/>
 *                         &lt;enumeration value="ChocolateWithFilling"/>
 *                         &lt;enumeration value="ChocolateWithoutFilling"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="ingredients">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="water" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *                             &lt;element name="sugar" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *                             &lt;element name="fructose" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *                             &lt;element name="chocolateType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="vanillin" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="value">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="proteins" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="fats" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="carbohydrates" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="production" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "candy"
})
@XmlRootElement(name = "Root")
public class Root {

    @XmlElement(required = true)
    protected List<Root.Candy> candy;

    /**
     * Gets the value of the candy property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the candy property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCandy().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Root.Candy }
     * 
     * 
     */
    public List<Root.Candy> getCandy() {
        if (candy == null) {
            candy = new ArrayList<Root.Candy>();
        }
        return this.candy;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="energy" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="type">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="Caramel"/>
     *               &lt;enumeration value="Iris"/>
     *               &lt;enumeration value="Chocolate"/>
     *               &lt;enumeration value="ChocolateWithFilling"/>
     *               &lt;enumeration value="ChocolateWithoutFilling"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="ingredients">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="water" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
     *                   &lt;element name="sugar" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
     *                   &lt;element name="fructose" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
     *                   &lt;element name="chocolateType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="vanillin" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="value">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="proteins" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="fats" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="carbohydrates" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="production" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "name",
        "energy",
        "type",
        "ingredients",
        "value",
        "production"
    })
    public static class Candy {

        @XmlElement(required = true)
        protected String name;
        protected int energy;
        @XmlElement(required = true)
        protected String type;
        @XmlElement(required = true)
        protected Root.Candy.Ingredients ingredients;
        @XmlElement(required = true)
        protected Root.Candy.Value value;
        @XmlElement(required = true)
        protected String production;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the energy property.
         * 
         */
        public int getEnergy() {
            return energy;
        }

        /**
         * Sets the value of the energy property.
         * 
         */
        public void setEnergy(int value) {
            this.energy = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

        /**
         * Gets the value of the ingredients property.
         * 
         * @return
         *     possible object is
         *     {@link Root.Candy.Ingredients }
         *     
         */
        public Root.Candy.Ingredients getIngredients() {
            return ingredients;
        }

        /**
         * Sets the value of the ingredients property.
         * 
         * @param value
         *     allowed object is
         *     {@link Root.Candy.Ingredients }
         *     
         */
        public void setIngredients(Root.Candy.Ingredients value) {
            this.ingredients = value;
        }

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link Root.Candy.Value }
         *     
         */
        public Root.Candy.Value getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link Root.Candy.Value }
         *     
         */
        public void setValue(Root.Candy.Value value) {
            this.value = value;
        }

        /**
         * Gets the value of the production property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProduction() {
            return production;
        }

        /**
         * Sets the value of the production property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProduction(String value) {
            this.production = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="water" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
         *         &lt;element name="sugar" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
         *         &lt;element name="fructose" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
         *         &lt;element name="chocolateType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="vanillin" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "water",
            "sugar",
            "fructose",
            "chocolateType",
            "vanillin"
        })
        public static class Ingredients {

            protected Float water;
            protected Float sugar;
            protected Float fructose;
            protected String chocolateType;
            protected Float vanillin;

            /**
             * Gets the value of the water property.
             * 
             * @return
             *     possible object is
             *     {@link Float }
             *     
             */
            public Float getWater() {
                return water;
            }

            /**
             * Sets the value of the water property.
             * 
             * @param value
             *     allowed object is
             *     {@link Float }
             *     
             */
            public void setWater(Float value) {
                this.water = value;
            }

            /**
             * Gets the value of the sugar property.
             * 
             * @return
             *     possible object is
             *     {@link Float }
             *     
             */
            public Float getSugar() {
                return sugar;
            }

            /**
             * Sets the value of the sugar property.
             * 
             * @param value
             *     allowed object is
             *     {@link Float }
             *     
             */
            public void setSugar(Float value) {
                this.sugar = value;
            }

            /**
             * Gets the value of the fructose property.
             * 
             * @return
             *     possible object is
             *     {@link Float }
             *     
             */
            public Float getFructose() {
                return fructose;
            }

            /**
             * Sets the value of the fructose property.
             * 
             * @param value
             *     allowed object is
             *     {@link Float }
             *     
             */
            public void setFructose(Float value) {
                this.fructose = value;
            }

            /**
             * Gets the value of the chocolateType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getChocolateType() {
                return chocolateType;
            }

            /**
             * Sets the value of the chocolateType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setChocolateType(String value) {
                this.chocolateType = value;
            }

            /**
             * Gets the value of the vanillin property.
             * 
             * @return
             *     possible object is
             *     {@link Float }
             *     
             */
            public Float getVanillin() {
                return vanillin;
            }

            /**
             * Sets the value of the vanillin property.
             * 
             * @param value
             *     allowed object is
             *     {@link Float }
             *     
             */
            public void setVanillin(Float value) {
                this.vanillin = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="proteins" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *         &lt;element name="fats" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *         &lt;element name="carbohydrates" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "proteins",
            "fats",
            "carbohydrates"
        })
        public static class Value {

            protected float proteins;
            protected float fats;
            protected float carbohydrates;

            /**
             * Gets the value of the proteins property.
             * 
             */
            public float getProteins() {
                return proteins;
            }

            /**
             * Sets the value of the proteins property.
             * 
             */
            public void setProteins(float value) {
                this.proteins = value;
            }

            /**
             * Gets the value of the fats property.
             * 
             */
            public float getFats() {
                return fats;
            }

            /**
             * Sets the value of the fats property.
             * 
             */
            public void setFats(float value) {
                this.fats = value;
            }

            /**
             * Gets the value of the carbohydrates property.
             * 
             */
            public float getCarbohydrates() {
                return carbohydrates;
            }

            /**
             * Sets the value of the carbohydrates property.
             * 
             */
            public void setCarbohydrates(float value) {
                this.carbohydrates = value;
            }

        }

    }

}
